In [1]:
import pandas as pd
import joblib
import shap
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/processed/ltv_dataset.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,InternetService,Contract,MonthlyCharges,TotalCharges,Churn,LTV
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,Month-to-month,29.85,29.85,No,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,One year,56.95,1889.50,No,1936.30
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Month-to-month,53.85,108.15,Yes,107.70
3,7795-CFOCW,Male,0,No,No,45,No,DSL,One year,42.30,1840.75,No,1903.50
4,9237-HQITU,Female,0,No,No,2,Yes,Fiber optic,Month-to-month,70.70,151.65,Yes,141.40

In [3]:
#Remove columns that should not be used for prediction.

X = df.drop(columns=["LTV", "customerID"])

X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,InternetService,Contract,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,DSL,Month-to-month,29.85,29.85,No
1,Male,0,No,No,34,Yes,DSL,One year,56.95,1889.50,No
2,Male,0,No,No,2,Yes,DSL,Month-to-month,53.85,108.15,Yes
3,Male,0,No,No,45,No,DSL,One year,42.30,1840.75,No
4,Female,0,No,No,2,Yes,Fiber optic,Month-to-month,70.70,151.65,Yes

In [4]:
#Load the Trained Churn Model
model = joblib.load("../models/churn_model.pkl")

model

LogisticRegression(max_iter=2000, solver='liblinear')

In [5]:
#Create the SHAP Explainer
explainer = shap.Explainer(model)

TypeError: The passed model is not callable and cannot be analyzed directly with the given masker! Model: LogisticRegression(max_iter=2000, solver='liblinear')

In [ ]:
#Generate SHAP Values

#To make computation faster, use a sample of the data.

sample = X.sample(200, random_state=42)

shap_values = explainer(sample)

In [6]:
#Create the SHAP Beeswarm Summary Plot
shap.plots.beeswarm(shap_values)

NameError: name 'shap_values' is not defined

In [7]:
#Save the Beeswarm Plot
plt.savefig(
    "../docs/images/shap_summary_beeswarm.png",
    bbox_inches="tight"
)

plt.close()

FileNotFoundError: [Errno 2] No such file or directory: '../docs/images/shap_summary_beeswarm.png'

In [8]:
#Create the SHAP Bar Plot
shap.plots.bar(shap_values)

NameError: name 'shap_values' is not defined

In [9]:
#Save the Bar Plot
plt.savefig(
    "../docs/images/shap_summary_bar.png",
    bbox_inches="tight"
)

plt.close()

FileNotFoundError: [Errno 2] No such file or directory: '../docs/images/shap_summary_bar.png'

In [ ]:
## Day 16 Conclusion

# The SHAP summary plots provide a global explanation of the churn model.

# Key observations:

# - Features at the top have the greatest influence on predictions.
# - The beeswarm plot shows both feature importance and the direction of impact.
# - The bar plot ranks features by their average contribution to the model.

# These visualizations help explain why the model predicts churn for different customers.